title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://0gon.github.io

aux_links:
  Template Repository: https://github.com/0gon/jtd
