#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/member_db
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

#spring:
#  datasource:
#    url: jdbc:mariadb://localhost:3306/member_db
#    username: root
#    password: root1234
#    driver-class-name: org.mariadb.jdbc.Driver

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/member_db
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver