services:
  database:
    container_name: h2
    image: oscarfonts/h2:latest
    ports:
      - 1521:1521
      - 8082:81
    environment:
      H2_OPTIONS: -ifNotExists -web -webAllowOthers
    volumes:
      - ./h2/:/opt/h2-data
    restart: always

  application:
    container_name: main-app
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://h2:1521/demo
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD:
    depends_on:
      - database