server:
  port: 9005


spring:
  profiles:
    include: local    # application-home.yml ? ????

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        #format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
        #배치 인서트
        jdbc:
          batch_size: 10
  application:
    name: feed-service

upload:
  #path: "/Users/yudong-yeob/desktop/filetest"    # MAC 파일 경로
  path: "C:/Users/User/Desktop/filetest"          # Windows 파일 경로

