server:
  port: 8083

spring:
  #kafka 설정
  kafka:
    bootstrap-servers: localhost:9092
    consumer: # 소비자
      group-id: chat-group                                                                      # 변경 필요
      auto-offset-reset: earliest                                                               # 카프카를 처음 시작하거나 커밋된 오프셋이 없을때 읽기 시작할 포인트 설정, earliest(오래된 메시지부터) latest(최근 메시지부터), none(없으면 오류)
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer                # 메시지 키를 역직렬화, kafka는 메시지를 바이트 배열로 전송하므로 객체로 변환 필요
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer              # 역직렬화
    producer: # 생산자
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  # DB 설정
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/testDB/testdc
    username: sa
    password:

# JPA 설정
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console

  # Redis 설정
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
logging:
  level:
    org.springframework.cache: DEBUG
    org.springframework.data.redis: DEBUG
